shard: shardname
day-length-ticks: 1000

disable-shard-teleports: false

spawnWidth: 2
spawnHeight: 2
centreX: 0
centreZ: 0

sql:
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "civrealms"