name: ${name}
version: ${version}
main: com.civrealms.plugin.bukkit.CivRealmsPlugin
author: Okx

commands:
  boatinventory:
    aliases: [binv, bi]
    usage: /<command> <page>
  restore:
    aliases: [invr]
    usage: /<command> <id>
    permission: civrealms.command.restore

permissions:
  civrealms.command.restore:
    default: op